name: qleon
description: Private, secure chat application built with Flutter & Firebase
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ðŸ”¥ Firebase Core
  firebase_core: ^3.6.0
  firebase_auth: ^5.4.0
  cloud_firestore: ^5.6.0
  firebase_storage: ^12.4.0
  firebase_messaging: ^15.2.0
  shared_preferences: ^2.0.15

  # ðŸ” Security & Encryption
  flutter_secure_storage: ^9.2.2
  cryptography: ^2.7.0
  pointycastle: ^3.9.0

  # ðŸ§  State Management & DI
  flutter_riverpod: ^2.5.1
  get_it: ^8.0.3

  # ðŸŒ Connectivity
  connectivity_plus: ^6.1.0

  # ðŸŽ¨ UI Helpers
  cupertino_icons: ^1.0.8
  intl: ^0.18.0
  mobile_scanner: ^5.0.0
  qr_flutter: ^4.1.0
  flutter_launcher_icons: ^0.13.1
  image_picker: ^1.1.1
  animations: ^2.0.6
  shimmer: ^3.0.0
  provider: ^6.0.0
  uuid: ^4.5.2

  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.5.0
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true

  assets:
  - assets/LICENSE

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon.png"